### ISSUE TITLE
contact us / report a bug - page displays code when message sent, crashes if run in IIS

### ISSUE THREAD

**Issue by cbarrieau232** [cbshashank/swegroup-4#42]
When clicking 'submit' on contact us (running outside of IIS), the page displays  code when the message is sent (see attached)
![contactus](https://cloud.githubusercontent.com/assets/14844945/11450044/a4b2d0be-955b-11e5-8dce-7da7220a7639.png)

When clicking 'submit' on contact us in IIS, the page displays the following:
![contactus_iis](https://cloud.githubusercontent.com/assets/14844945/11450047/00e931c0-955c-11e5-80f1-8eda5bb019e4.png)

**Comment by sag129** [comment]
I see. I know why.  To create the actual emails, you have to put in your BU id and pw.  It works correctly if you do that.  The code I committed DOES NOT contain **my** personal email id and pw.  That's unsafe to share with everyone.  Look in the .asp pages and search for password.  You'll find the section of code where you have to fill in the values for the username, pw variables.

**Comment by cbarrieau232** [comment]
Ah OK.  I will retest this weekend doing that.

**Comment by sag129** [comment]
I will create a new gmail address for our website and will have that gmail account do the emails.

**Comment by cbarrieau232** [comment]
Still seeing both errors with the new gmail account - will need to investigate what is going on.

**Comment by cbarrieau232** [comment]
Think this may be a configuration issue on my machine - I did not have ASP.NET support installed in IIS.  Updating now.

**Comment by sag129** [comment]
Use hotmail or yahoo email address.

**Comment by sag129** [comment]
Gmail CANNOT do ASP emails.  The code works but gmail refuses to let ASP emails happen for security reasons

**Comment by sag129** [comment]
<img width="481" alt="cannot use gmail for asp email" src="https://cloud.githubusercontent.com/assets/12366059/11604978/41cd2046-9ac2-11e5-9b7c-76e951cf749d.png">

**Comment by sag129** [comment]
Fixed and tested.
